# Generated by Django 6.0.2 on 2026-03-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField()),
                ("first_name", models.CharField()),
                ("street_number", models.CharField()),
                ("street_name", models.CharField()),
                ("apartment_number", models.CharField()),
                ("zip_code", models.CharField()),
                ("date_of_birth", models.DateField()),
                ("date_of_registration", models.DateField()),
                ("party_affiliation", models.CharField(max_length=2)),
                ("precinct_number", models.CharField()),
                ("v20state", models.BooleanField(default=False)),
                ("v21town", models.BooleanField(default=False)),
                ("v21primary", models.BooleanField(default=False)),
                ("v22general", models.BooleanField(default=False)),
                ("v23town", models.BooleanField(default=False)),
                ("voter_score", models.IntegerField(default=0)),
            ],
        ),
    ]
