# Generated by Django 6.0.2 on 2026-03-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="apartment_number",
            field=models.CharField(blank=True, null=True),
        ),
    ]
