# Generated by Django 6.0.2 on 2026-02-20 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loc", models.URLField()),
                ("desc", models.TextField(max_length=500)),
                ("alt", models.CharField(default="")),
                ("aid", models.CharField(max_length=150)),
                ("slug", models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateField(auto_now_add=True)),
                ("caption", models.CharField(max_length=20)),
                ("profile", models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="bio_text",
            new_name="bio",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="profile_image_url",
            new_name="icon",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="display_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="join_date",
        ),
        migrations.AddField(
            model_name="profile",
            name="join",
            field=models.TimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="nick",
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
