# Generated by Django 6.0.2 on 2026-02-20 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0002_photo_post_rename_bio_text_profile_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mini_insta.profile"
            ),
        ),
    ]
