# Generated by Django 6.0.2 on 2026-02-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0003_alter_post_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="join",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
