# Generated by Django 6.0.2 on 2026-02-21 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0004_alter_profile_join"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="join",
        ),
    ]
