# Generated by Django 6.0.2 on 2026-02-21 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0005_remove_profile_join"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="nick",
            new_name="display_name",
        ),
    ]
