# Generated by Django 6.0.2 on 2026-02-21 00:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0006_rename_nick_profile_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
