# Generated by Django 6.0.2 on 2026-02-21 00:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0007_profile_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="timestamp",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
