# Generated by Django 6.0.2 on 2026-02-21 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0008_alter_post_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="aid",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="alt",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="slug",
        ),
        migrations.AddField(
            model_name="photo",
            name="post",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="mini_insta.post",
            ),
            preserve_default=False,
        ),
    ]
