# Generated by Django 6.0.2 on 2026-02-21 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mini_insta",
            "0009_remove_photo_aid_remove_photo_alt_remove_photo_slug_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="profile",
        ),
        migrations.DeleteModel(
            name="Photo",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
