# Generated by Django 6.0.2 on 2026-02-21 01:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0011_post_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="desc",
        ),
        migrations.AddField(
            model_name="photo",
            name="timestamp",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
