# Generated by Django 6.0.2 on 2026-03-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0012_remove_photo_desc_photo_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="media",
            field=models.ImageField(default="", upload_to=""),
        ),
        migrations.AlterField(
            model_name="photo",
            name="loc",
            field=models.URLField(blank=True),
        ),
    ]
