# Generated by Django 6.0.2 on 2026-02-26 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollectionArtist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collectionArtistName", models.CharField(max_length=128)),
                ("collectionArtistLocation", models.CharField(max_length=128)),
                ("collectionArtistDescription", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="TestList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("testListDesc", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collectionTitle", models.CharField(max_length=128)),
                ("collectionDescription", models.CharField(max_length=500)),
                ("collectionMediaType", models.CharField(max_length=128)),
                ("collectionYear", models.IntegerField()),
                ("collectionTracks", models.IntegerField()),
                ("collectionDisks", models.IntegerField()),
                ("collectionFiles", models.FileField(upload_to="")),
                ("collectionCover", models.ImageField(upload_to="")),
                (
                    "collectionArtist",
                    models.ManyToManyField(to="testpages.collectionartist"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollectionGenreDescriptor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descriptor", models.CharField(max_length=128)),
                (
                    "artists",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testpages.collectionartist",
                    ),
                ),
                (
                    "collections",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testpages.collection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("testInt", models.IntegerField()),
                ("testChar", models.CharField(max_length=50)),
                (
                    "testList",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testpages.testlist",
                    ),
                ),
            ],
        ),
    ]
