# Generated by Django 6.0.2 on 2026-04-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testpages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trackFile", models.FileField(upload_to="")),
            ],
        ),
    ]
