# Generated by Django 6.0.2 on 2026-04-25 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testpages", "0003_remove_testmodel_testlist_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("is_official", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_file", models.FileField(upload_to="")),
            ],
        ),
        migrations.RemoveField(
            model_name="collection",
            name="collectionArtist",
        ),
        migrations.RemoveField(
            model_name="collectiongenredescriptor",
            name="collections",
        ),
        migrations.RemoveField(
            model_name="collectiongenredescriptor",
            name="artists",
        ),
        migrations.DeleteModel(
            name="CollectionTrack",
        ),
        migrations.AddField(
            model_name="profile",
            name="display_name",
            field=models.CharField(default="", max_length=32),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_description",
            field=models.TextField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_icon",
            field=models.ImageField(default="", upload_to=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="django_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="uploader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="testpages.profile",
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="testpages.artist"
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to="testpages.album",
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="artist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artist_tracks",
                to="testpages.artist",
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="features",
            field=models.ManyToManyField(
                blank=True, related_name="features", to="testpages.artist"
            ),
        ),
        migrations.DeleteModel(
            name="Collection",
        ),
        migrations.DeleteModel(
            name="CollectionArtist",
        ),
        migrations.DeleteModel(
            name="CollectionGenreDescriptor",
        ),
    ]
