# Generated by Django 6.0.2 on 2026-04-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testpages", "0004_album_artist_track_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="is_private",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="track",
            name="disc_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="track_cover",
            field=models.ImageField(blank=True, null=True, upload_to="covers/"),
        ),
        migrations.AddField(
            model_name="track",
            name="track_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
