# Generated by Django 6.0.2 on 2026-04-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "testpages",
            "0005_album_is_private_track_disc_number_track_track_cover_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_description",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_icon",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
