# Generated by Django 6.0.2 on 2026-04-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testpages", "0006_alter_profile_profile_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="track",
            old_name="disc_number",
            new_name="disk_number",
        ),
        migrations.AddField(
            model_name="album",
            name="mbid",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="track",
            name="track_length",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="track_title",
            field=models.CharField(default="None"),
            preserve_default=False,
        ),
    ]
